[package]
name = "migrations"
version = "0.1.0"
rust_version = "1.56.0"
edition = "2021"
publish = false

[lib]
name = "migrations"
path = "src/lib.rs"

[dependencies]
entities = { path = "../entities" }
sea-orm-migration = { version = "^0.8.0" }
