[template]
cargo_generate_version = ">=0.10.0"

[placeholders.description]
type = "string"
prompt = "Project description?"

[placeholders.fast-compiles]
type = "bool"
prompt = "Enable fast compiles for debug? (note: debug in vscode does not work!)"
default = false

[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)?"
# The username cannot end with a hyphen, too, but
# this requirement is not captured by the regex at the moment.
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.rtm-es-memory]
type = "bool"
prompt = "Use memory Event Store for RTM?"
default = false

mysql= "bool"
mysqllt = false

[placeholders.rtm-es-nats]
type = "bool"
prompt = "Use NATS-JetStream Event Store for RTM?"
default = false

[placeholders.rtm-es-postgresql]
type = "bool"
prompt = "Use PostgreSQL Event Store for RTM?"
default = false

[conditional.'sql == true']
sql-migrations = {type = "string",prompt = "Which SQL migration tool?",choices = ["Refinery", "SeaORM"],default = "Refinery"}
sql-orm = {type = "string",prompt = "Which SQL ORM tool?",choices = ["SeaORM"],default = "SeaORM"}
sql-vendor = {type = "string",prompt = "Which SQL vendor?",choices = ["mysql", "postgresql", "sqlite"],default = "sqlite",}
db-host = {type = "string", prompt = "Database hostname", regex = "^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$"}
db-name = {type = "string", prompt = "Database name", regex = "^[a-zA-Z_][a-zA-Z0-9_]*$"}
db-pass = {type = "string", prompt = "Database password - at least eight characters with at least one lower & upper case letter, digit and special character.", regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9])(?=.{8,})$"}
db-port = {type = "string", prompt = "Database port", regex = "^[0-9]+$"}
db-schema = {type = "string", prompt = "Database schema", default = "rtm", regex = "^[a-zA-Z_][a-zA-Z0-9_]*$"}
db-user = {type = "string", prompt = "Database username", regex = "^(?=[a-zA-Z0-9._]{8,20}$)(?!.*[_.]{2})[^_.].*[^_.]$"}

[conditional.'sql-orm == "SeaORM"']
rename = {entities-seaorm = "entities"}
async = { type = "string", prompt = "Which async runtime?", choices = [ "actix", "async-std", "tokio", ], default = "async-std",}
tls = { type = "string", prompt = "Which TLS crate?", choices = [ "native-tls", "Rustls", ], default = "rustls",}
mock = {type = "bool", prompt = "Mock interface for unit testing?", default = true }

[conditional.'fast-compiles == false']
ignore = ["rust-toolchain.toml", ".cargo"]
