[template]
cargo_generate_version = ">=0.10.0"

[placeholders.description]
type = "string"
prompt = "Project description?"

[placeholders.fast-compiles]
type = "bool"
prompt = "Enable fast compiles for debug? (note: debug in vscode does not work!)"
default = false

[placeholders.gh-username]
type = "string"
prompt = "GitHub username (or organization)?"
# The username cannot end with a hyphen, too, but
# this requirement is not captured by the regex at the moment.
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[placeholders.rtm-es-memory]
type = "bool"
prompt = "Use memory Event Store for RTM?"
default = false

mysql= "bool"
mysqllt = false

[placeholders.rtm-es-nats]
type = "bool"
prompt = "Use NATS-JetStream Event Store for RTM?"
default = false

[placeholders.rtm-es-postgresql]
type = "bool"
prompt = "Use PostgreSQL Event Store for RTM?"
default = false

[conditional.'sql-orm == "SeaORM"']
rename = {entities-seaorm = "entities"}
async = { type = "string", prompt = "Which async runtime?", choices = [ "actix", "async-std", "tokio", ], default = "async-std",}
tls = { type = "string", prompt = "Which TLS crate?", choices = [ "native-tls", "Rustls", ], default = "rustls",}
mock = {type = "bool", prompt = "Mock interface for unit testing?", default = true }

[conditional.'fast-compiles == false']
ignore = ["rust-toolchain.toml", ".cargo"]
